package com.klwork.spring.vertx.common;

/**
 * Created by young on 16/1/2.
 */

public enum ResultCode {

    SUCCESS(100),

    SYS_REQ_PARAM_CONTENT_OVERFLOW(201),

    SYS_REQ_PARAM_INVALID(202),

    SYS_REQ_TOKEN_ERROR(211),

    SYS_NETWORK_ERROR(901),

    SYS_UNKONW_ERROR(999),

    VEHICLE_NOT_EXISTS(1001),

    VEHICLE_ALREADY_BIND_SCHEDULE(1002),

    DRIVER_NOT_EXISTS(1101),

    DRIVER_ALREADY_BIND_SCHEDULE(1102),

    DRIVER_ALREADY_BIND_VEHICLE(1103),

    DRIVER_FILE_NOT_EXITS(1104),

    TELEMATICS_NOT_EXISTS(1201),

    TELEMATICS_ALREADY_BIND_VEHICLE(1202),

    TELEMATICS_BIND_ERROR_VEHICLE(1203),

    ORGANIZATION_NOT_EXISTS(1301),

    ORGANIZATION_PARENTID_SAME_SELFID(1302),

    POI_NOT_EXISTS(1401),

    POI_ALREADY_BIND_ROUTE(1402),

    POI_ALREADY_EXIT(1403),

    ROUTE_NOT_EXISTS(1501),

    ROUTE_ALREADY_BIND_SCHEDULE(1502),

    ROUTE_ALREADY_EXIT_DB(1503),

    CONTRACT_NOT_EXISTS(1601),

    CONTRACT_ALREADY_POPULATED(1602),

    CONTRACT_STILL_VALID(1603),

    CONTRACT_VALID_FOR_CUSTOMER(1604),

    CONTRACT_JOB_TEMPLATE_NOT_EXISTS(1701),

    JOB_NOT_EXISTS(1801),

    JOB_NO_EXECUTE(1802),

    SUBCONTRACT_NOT_EXISTS(1901),

    CUSTOMER_NOT_EXISTS(2001),

    PARSE_ERROR(2101),

    PARSE_STRING2INT_ERROR(2102),

    PARSE_HEX2LONG_ERROR(2103),

    USER_NOT_EXIT(2201),

    USER_NOT_EXIST(2202),

    TOKEN_NOT_EXIT(400);

    ResultCode(int code) {
        this.code = code;
    }

    public int code() {
        return this.code;
    }

    private int code;
}
